import {DropIcon as icon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'
import {memberType} from './member'
import {required, requiredArray} from '../validations'

const brewStyles = [
  {title: '1A. American Light Lager', value: 'American Light Lager'},
  {title: '1B. American Lager', value: 'American Lager'},
  {title: '1C. Cream Ale', value: 'Cream Ale'},
  {title: '1D. American Wheat Beer', value: 'American Wheat Beer'},
  {title: '2A. International Pale Lager', value: 'International Pale Lager'},
  {title: '2B. International Amber Lager', value: 'International Amber Lager'},
  {title: '2C. International Dark Lager', value: 'International Dark Lager'},
  {title: '3A. Czech Pale Lager', value: 'Czech Pale Lager'},
  {title: '3B. Czech Premium Pale Lager', value: 'Czech Premium Pale Lager'},
  {title: '3C. Czech Amber Lager', value: 'Czech Amber Lager'},
  {title: '3D. Czech Dark Lager', value: 'Czech Dark Lager'},
  {title: '4A. Munich Helles', value: 'Munich Helles'},
  {title: '4B. Festbier', value: 'Festbier'},
  {title: '4C. Helles Bock', value: 'Helles Bock'},
  {title: '5A. German Leichtbier', value: 'German Leichtbier'},
  {title: '5B. Kölsch', value: 'Kölsch'},
  {title: '5C. German Helles Exportbier', value: 'German Helles Exportbier'},
  {title: '5D. German Pils', value: 'German Pils'},
  {title: '6A. Märzen', value: 'Märzen'},
  {title: '6B. Rauchbier', value: 'Rauchbier'},
  {title: '6C. Dunkles Bock', value: 'Dunkles Bock'},
  {title: '7A. Vienna Lager', value: 'Vienna Lager'},
  {title: '7B. Altbier', value: 'Altbier'},
  {title: '7C. Kellerbier: Amber Kellerbier', value: 'Kellerbier: Amber Kellerbier'},
  {title: '7C. Kellerbier: Pale Kellerbier', value: 'Kellerbier: Pale Kellerbier'},
  {title: '8A. Munich Dunkel', value: 'Munich Dunkel'},
  {title: '8B. Schwarzbier', value: 'Schwarzbier'},
  {title: '9A. Doppelbock', value: 'Doppelbock'},
  {title: '9B. Eisbock', value: 'Eisbock'},
  {title: '9C. Baltic Porter', value: 'Baltic Porter'},
  {title: '10A. Weissbier', value: 'Weissbier'},
  {title: '10B. Dunkles Weissbier', value: 'Dunkles Weissbier'},
  {title: '10C. Weizenbock', value: 'Weizenbock'},
  {title: '11A. Ordinary Bitter', value: 'Ordinary Bitter'},
  {title: '11B. Best Bitter', value: 'Best Bitter'},
  {title: '11C. Strong Bitter', value: 'Strong Bitter'},
  {title: '12A. British Golden Ale', value: 'British Golden Ale'},
  {title: '12B. Australian Sparkling Ale', value: 'Australian Sparkling Ale'},
  {title: '12C. English IPA', value: 'English IPA'},
  {title: '13A. Dark Mild', value: 'Dark Mild'},
  {title: '13B. British Brown Ale', value: 'British Brown Ale'},
  {title: '13C. English Porter', value: 'English Porter'},
  {title: '14A. Scottish Light', value: 'Scottish Light'},
  {title: '14B. Scottish Heavy', value: 'Scottish Heavy'},
  {title: '14C. Scottish Export', value: 'Scottish Export'},
  {title: '15A. Irish Red Ale', value: 'Irish Red Ale'},
  {title: '15B. Irish Stout', value: 'Irish Stout'},
  {title: '15C. Irish Extra Stout', value: 'Irish Extra Stout'},
  {title: '16A. Sweet Stout', value: 'Sweet Stout'},
  {title: '16B. Oatmeal Stout', value: 'Oatmeal Stout'},
  {title: '16C. Tropical Stout', value: 'Tropical Stout'},
  {title: '16D. Foreign Extra Stout', value: 'Foreign Extra Stout'},
  {title: '17A. British Strong Ale', value: 'British Strong Ale'},
  {title: '17B. Old Ale', value: 'Old Ale'},
  {title: '17C. Wee Heavy', value: 'Wee Heavy'},
  {title: '17D. English Barleywine', value: 'English Barleywine'},
  {title: '18A. Blonde Ale', value: 'Blonde Ale'},
  {title: '18B. American Pale Ale', value: 'American Pale Ale'},
  {title: '19A. American Amber Ale', value: 'American Amber Ale'},
  {title: '19B. California Common', value: 'California Common'},
  {title: '19C. American Brown Ale', value: 'American Brown Ale'},
  {title: '20A. American Porter', value: 'American Porter'},
  {title: '20B. American Stout', value: 'American Stout'},
  {title: '20C. Imperial Stout', value: 'Imperial Stout'},
  {title: '21A. American IPA', value: 'American IPA'},
  {title: '21B. Specialty IPA: Belgian IPA', value: 'Specialty IPA: Belgian IPA'},
  {title: '21B. Specialty IPA: Black IPA', value: 'Specialty IPA: Black IPA'},
  {title: '21B. Specialty IPA: Brown IPA', value: 'Specialty IPA: Brown IPA'},
  {title: '21B. Specialty IPA: Brut IPA', value: 'Specialty IPA: Brut IPA'},
  {title: '21B. Specialty IPA: Red IPA', value: 'Specialty IPA: Red IPA'},
  {title: '21B. Specialty IPA: Rye IPA', value: 'Specialty IPA: Rye IPA'},
  {title: '21B. Specialty IPA: White IPA', value: 'Specialty IPA: White IPA'},
  {title: '21C. Hazy IPA', value: 'Hazy IPA'},
  {title: '22A. Double IPA', value: 'Double IPA'},
  {title: '22B. American Strong Ale', value: 'American Strong Ale'},
  {title: '22C. American Barleywine', value: 'American Barleywine'},
  {title: '22D. Wheatwine', value: 'Wheatwine'},
  {title: '23A. Berliner Weisse', value: 'Berliner Weisse'},
  {title: '23B. Flanders Red Ale', value: 'Flanders Red Ale'},
  {title: '23C. Oud Bruin', value: 'Oud Bruin'},
  {title: '23D. Lambic', value: 'Lambic'},
  {title: '23E. Gueuze', value: 'Gueuze'},
  {title: '23F. Fruit Lambic', value: 'Fruit Lambic'},
  {title: '23G. Gose', value: 'Gose'},
  {title: '24A. Witbier', value: 'Witbier'},
  {title: '24B. Belgian Pale Ale', value: 'Belgian Pale Ale'},
  {title: '24C. Bière de Garde', value: 'Bière de Garde'},
  {title: '25A. Belgian Blond Ale', value: 'Belgian Blond Ale'},
  {title: '25B. Saison', value: 'Saison'},
  {title: '25C. Belgian Golden Strong Ale', value: 'Belgian Golden Strong Ale'},
  {title: '26A. Trappist Single', value: 'Trappist Single'},
  {title: '26B. Belgian Dubbel', value: 'Belgian Dubbel'},
  {title: '26C. Belgian Tripel', value: 'Belgian Tripel'},
  {title: '26D. Belgian Dark Strong Ale', value: 'Belgian Dark Strong Ale'},
  {title: '27A. Historical Beer: Gose', value: 'Historical Beer: Gose'},
  {title: '27A. Historical Beer: Kellerbier', value: 'Historical Beer: Kellerbier'},
  {title: '27A. Historical Beer: Kentucky Common', value: 'Historical Beer: Kentucky Common'},
  {title: '27A. Historical Beer: Lichtenhainer', value: 'Historical Beer: Lichtenhainer'},
  {title: '27A. Historical Beer: London Brown Ale', value: 'Historical Beer: London Brown Ale'},
  {title: '27A. Historical Beer: Piwo Grodziskie', value: 'Historical Beer: Piwo Grodziskie'},
  {
    title: '27A. Historical Beer: Pre-Prohibition Lager',
    value: 'Historical Beer: Pre-Prohibition Lager',
  },
  {
    title: '27A. Historical Beer: Pre-Prohibition Porter',
    value: 'Historical Beer: Pre-Prohibition Porter',
  },
  {title: '27A. Historical Beer: Roggenbier', value: 'Historical Beer: Roggenbier'},
  {title: '27A. Historical Beer: Sahti', value: 'Historical Beer: Sahti'},
  {title: '28A. Brett Beer', value: 'Brett Beer'},
  {title: '28B. Mixed-Fermentation Sour Beer', value: 'Mixed-Fermentation Sour Beer'},
  {title: '28C. Wild Specialty Beer', value: 'Wild Specialty Beer'},
  {title: '28D. Straight Sour Beer', value: 'Straight Sour Beer'},
  {title: '29A. Fruit Beer', value: 'Fruit Beer'},
  {title: '29B. Fruit and Spice Beer', value: 'Fruit and Spice Beer'},
  {title: '29C. Specialty Fruit Beer', value: 'Specialty Fruit Beer'},
  {title: '29D. Grape Ale', value: 'Grape Ale'},
  {title: '30A. Spice, Herb, or Vegetable Beer', value: 'Spice, Herb, or Vegetable Beer'},
  {title: '30B. Autumn Seasonal Beer', value: 'Autumn Seasonal Beer'},
  {title: '30C. Winter Seasonal Beer', value: 'Winter Seasonal Beer'},
  {title: '30D. Specialty Spice Beer', value: 'Specialty Spice Beer'},
  {title: '31A. Alternative Grain Beer', value: 'Alternative Grain Beer'},
  {title: '31B. Alternative Sugar Beer', value: 'Alternative Sugar Beer'},
  {title: '32A. Classic Style Smoked Beer', value: 'Classic Style Smoked Beer'},
  {title: '32B. Specialty Smoked Beer', value: 'Specialty Smoked Beer'},
  {title: '33A. Wood-Aged Beer', value: 'Wood-Aged Beer'},
  {title: '33B. Specialty Wood-Aged Beer', value: 'Specialty Wood-Aged Beer'},
  {title: '34A. Clone Beer', value: 'Clone Beer'},
  {title: '34B. Mixed-Style Beer', value: 'Mixed-Style Beer'},
  {title: '34C. Experimental Beer', value: 'Experimental Beer'},
  {title: 'M1A. Dry Mead', value: 'Dry Mead'},
  {title: 'M1B. Semi-Sweet Mead', value: 'Semi-Sweet Mead'},
  {title: 'M1C. Sweet Mead', value: 'Sweet Mead'},
  {title: 'M2A. Cyser', value: 'Cyser'},
  {title: 'M2B. Pyment', value: 'Pyment'},
  {title: 'M2C. Berry Mead', value: 'Berry Mead'},
  {title: 'M2D. Stone Fruit Mead', value: 'Stone Fruit Mead'},
  {title: 'M2E. Melomel', value: 'Melomel'},
  {title: 'M3A. Fruit and Spice Mead', value: 'Fruit and Spice Mead'},
  {title: 'M3B. Spice, Herb or Vegetable Mead', value: 'Spice, Herb or Vegetable Mead'},
  {title: 'M4A. Braggot', value: 'Braggot'},
  {title: 'M4B. Historical Mead', value: 'Historical Mead'},
  {title: 'M4C. Experimental Mead', value: 'Experimental Mead'},
  {title: 'C1A. New World Cider', value: 'New World Cider'},
  {title: 'C1B. English Cider', value: 'English Cider'},
  {title: 'C1C. French Cider', value: 'French Cider'},
  {title: 'C1D. New World Perry', value: 'New World Perry'},
  {title: 'C1E. Traditional Perry', value: 'Traditional Perry'},
  {title: 'C2A. New England Cider', value: 'New England Cider'},
  {title: 'C2B. Cider with Other Fruit', value: 'Cider with Other Fruit'},
  {title: 'C2C. Applewine', value: 'Applewine'},
  {title: 'C2D. Ice Cider', value: 'Ice Cider'},
  {title: 'C2E. Cider with Herbs/Spices', value: 'Cider with Herbs/Spices'},
  {title: 'C2F. Specialty Cider/Perry', value: 'Specialty Cider/Perry'},
]

export const brewType = defineType({
  name: 'brew',
  title: 'Brew',
  type: 'document',
  icon: icon,
  fields: [
    defineField({
      name: 'name',
      title: 'Recipe/Beer Name (optional)',
      type: 'string',
    }),
    defineField({
      name: 'brewer',
      title: 'Brewer',
      type: 'reference',
      to: [{type: memberType.name}],
    }),
    defineField({
      name: 'style',
      type: 'string',
      options: {
        list: brewStyles,
        layout: 'dropdown',
      },
      validation: required,
    }),
    defineField({
      name: 'ingredients',
      title: 'Ingredients',
      type: 'array',
      validation: requiredArray,
      of: [
        {
          type: 'object',
          fields: [
            {
              name: 'amount',
              type: 'number',
              validation: (Rule) => Rule.precision(2),
            },
            {
              name: 'unit',
              type: 'string',
              options: {
                list: [
                  {title: 'grams', value: 'g'},
                  {title: 'kilograms', value: 'kg'},
                  {title: 'milliliters', value: 'ml'},
                  {title: 'liters', value: 'l'},
                  {title: 'ounces', value: 'oz'},
                  {title: 'pounds', value: 'lb'},
                  {title: 'items', value: 'item'},
                  {title: 'packages', value: 'pkg'},
                ],
              },
            },
            {
              name: 'name',
              title: 'Ingredient Name',
              type: 'string',
            },
          ],
          preview: {
            select: {
              amount: 'amount',
              unit: 'unit',
              name: 'name',
            },
            prepare({amount, unit, name}) {
              return {
                title: `${amount} ${unit} of ${name}`,
              }
            },
          },
        },
      ],
    }),
    defineField({
      name: 'description',
      type: 'text',
    }),
    defineField({
      name: 'brewDates',
      type: 'object',
      fields: [
        defineField({
          name: 'brewDate',
          type: 'datetime',
          validation: required,
        }),
        defineField({
          name: 'yeastPrepDate',
          title: 'Yeast Prep Date (optional)',
          type: 'datetime',
        }),
        defineField({
          name: 'conditioningDate',
          title: 'Conditioning Date (optional)',
          type: 'datetime',
        }),
        defineField({
          name: 'endDate',
          type: 'datetime',
          validation: required,
        }),
      ],
    }),
    defineField({
      name: 'software',
      title: 'Software Used',
      type: 'string',
    }),
    defineField({
      name: 'equipment',
      title: 'Equipment Used',
      type: 'string',
    }),
  ],
  preview: {
    select: {
      title: 'name',
      brewer: 'brewer.name',
      style: 'style',
    },
    prepare({title, brewer, style}) {
      if (!brewer || !style) return {title: 'Untitled'}
      const firstName = brewer.split(' ')[0]

      return title
        ? {
            title: title,
            subtitle: `${firstName} - ${style}`,
          }
        : {
            title: `${firstName} - ${style}`,
          }
    },
  },
})
